version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: weblab_frontend
    restart: always
    ports:
      - "4000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: weblab-backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - .env

  mongodb:
    image: mongo:6.0.4
    container_name: weblab-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - weblab-db:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME:?error}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:?error}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:?error}
    env_file:
      - .env

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: weblab-mongo-express
    depends_on:
      - mongodb
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: weblab-mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER:?error}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD:?error}
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_VIEWER_USER:?error}
      ME_CONFIG_BASICAUTH:PASSWORD: ${DB_VIEWER_PASSWORD:?error}
    env_file:
      - .env

volumes:
  weblab-db: